### ISSUE TITLE
Maybe archive and point people to Apache Annotator?

### ISSUE THREAD

**Issue by BigBlueHat** [Treora/selector-state-frags#2]
https://github.com/apache/incubator-annotator/tree/master/packages/fragment-identifier

Would also be lovely to bring the tests from this repo over to Apache Annotator. 😸 
https://github.com/Treora/selector-state-frags/blob/master/test/test.js

Cheers!
🎩

**Comment by Treora** [comment]
Apparently the other way around. :)

I just incorporated some work we did in Apache Annotator’s now-abandoned module into this repository, perhaps it may still have use in some way.
